# Generated by Django 2.2.3 on 2019-07-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100)),
                ('speed_limit', models.CharField(max_length=50)),
                ('duration', models.DurationField()),
                ('prise', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Custmor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField()),
                ('gander', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('business', models.CharField(choices=[('Y', 'Yes'), ('N', 'NO')], max_length=10)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='desh.Plans')),
            ],
        ),
        migrations.CreateModel(
            name='Compalin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('custmor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='desh.Custmor')),
            ],
        ),
    ]
