# Generated by Django 2.2.3 on 2019-07-14 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custmor',
            name='region',
            field=models.CharField(choices=[('M.P.', 'M.P.'), ('Maharastra', 'Maharastra'), ('Bihar', 'Bihar')], default=12, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custmor',
            name='business',
            field=models.CharField(choices=[('Small', 'Small'), ('Learge', 'Learge'), ('No', 'NO')], max_length=10),
        ),
    ]
